CREATE TABLE `emotion_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`entityType` enum('meeting','interview') NOT NULL,
	`entityId` int NOT NULL,
	`timestamp` int NOT NULL,
	`happy` int DEFAULT 0,
	`sad` int DEFAULT 0,
	`angry` int DEFAULT 0,
	`surprised` int DEFAULT 0,
	`fearful` int DEFAULT 0,
	`disgusted` int DEFAULT 0,
	`neutral` int DEFAULT 0,
	`dominantEmotion` varchar(50),
	`attentionScore` int DEFAULT 0,
	`eyeContact` boolean DEFAULT false,
	`headPose` varchar(50),
	`bodyLanguage` text,
	`engagement` int DEFAULT 0,
	`confidence` int DEFAULT 0,
	`stress` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `emotion_analysis_id` PRIMARY KEY(`id`)
);
